version: "3.9"
networks:
  base:
    driver: bridge
services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=password
    networks:
      - base
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: gamer
      POSTGRES_PASSWORD: gamer
      POSTGRES_DB: game
    networks:
      - base
  gameserver:
    build: .
    environment:
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=gamer
      - POSTGRES_PASSWORD=gamer
      - POSTGRES_DB=game
    depends_on:
      - redis
      - postgres
    networks:
      - base
    volumes:
      - .:/app
    working_dir:
      /app
    command: make game-server-dev
  apiserver:
    build: .
    environment:
      - SERVER_URL=http://localhost:8080
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=gamer
      - POSTGRES_PASSWORD=gamer
      - POSTGRES_DB=game
    ports:
      - 8080:8080
    depends_on:
      - gameserver
    networks:
      - base
    volumes:
      - .:/app
    working_dir:
      /app
    command: make api-server-dev
