version: "3.9"
networks:
  base:
    driver: bridge
volumes:
  postgres:
services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./cache/config.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - base
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    networks:
      - base
  web:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - redis
      - postgres
    networks:
      - base
    volumes:
      - .:/app
    working_dir:
      /app
    command: sh -c './bin/dev.sh'
  load-test:
    build:
      context: .
      dockerfile: Dockerfile.load-test
    platform: linux/x86_64
    networks:
      - base
    ports:
      - '8125:8125'
    volumes:
      - .:/app
    working_dir: /app
