version: "3.9"
services:
  app:
    build: .
    environment:
      - GAME_MAP_SIZE=${GAME_MAP_SIZE}
    ports:
      - 8080:8080
  dev:
    image: golang:1.18
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir:
      /app
    command: make dev
