version: "3.9"
networks:
  base:
    driver: bridge
volumes:
  postgres:
services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=main
    networks:
      - base
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    networks:
      - base
  web:
    build: .
    environment:
      - SERVER_URL=http://localhost:8080
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=main
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
      - POSTGRES_DB=main
    ports:
      - 8080:8080
    depends_on:
      - redis
      - postgres
    networks:
      - base
    volumes:
      - .:/app
    working_dir:
      /app
    command: sh -c './script/init_database.sh && make dev'
