version: "3.9"
networks:
  base:
    driver: bridge
services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=password
    networks:
      - base
  computer:
    build: .
    environment:
      - APP=computer
      - GAME_MAP_SIZE=2000
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=password
    depends_on:
      - redis
    networks:
      - base
    volumes:
      - .:/app
    working_dir:
      /app
    command: make dev
  client:
    build: .
    environment:
      - APP=client
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=password
    ports:
      - 8080:8080
    depends_on:
      - computer
    networks:
      - base
    volumes:
      - .:/app
    working_dir:
      /app
    command: make dev
